import fs from 'fs';
import path from 'path';
import { projects } from '#velite';
import RadarChart from '@/components/RadarChart';

export default function Home() {
  // Load decoupled aggregated scores generated by the LLM Delta pipeline
  let radarData: any[] = [];
  try {
    const scoresPath = path.join(process.cwd(), 'public', 'scores.json');
    radarData = JSON.parse(fs.readFileSync(scoresPath, 'utf8'));
  } catch (error) {
    console.error("Failed to load scores.json", error);
  }

  // Filter Velite projects for mapping
  const workProjects = projects.filter(p => p.category === 'Work');
  const writingPosts = projects.filter(p => p.category === 'Writing');

  return (
    <main className="w-full flex-1 flex flex-col">
      
      {/* Ticker Section */}
      <div className="flex items-center gap-2 px-3 py-1.5 bg-[#EFEBE3] border-b-[0.5px] border-[#E0DAD0] text-[10px] font-medium tracking-[0.12em] uppercase text-[#999999]">
        momentum ticker <span className="bg-[#4CAF7E] text-[#F7F4EF] text-[9px] px-[7px] py-[2px] rounded-full tracking-[0.08em] ml-1">updated</span>
      </div>
      <div className="bg-[#1A1814] overflow-hidden py-[9px] border-b-[0.5px] border-[#2E2A25]">
        <div className="flex whitespace-nowrap animate-[ticker_28s_linear_infinite]">
          {[...Array(2)].map((_, i) => (
            <div key={i} className="contents">
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Now reading <span className="text-[#D4C9B8] font-medium">Designing Data-Intensive Applications</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Building <span className="text-[#D4C9B8] font-medium">churn prediction model in sklearn</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Learning <span className="text-[#D4C9B8] font-medium">dbt Core + Airflow orchestration</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Unwinding with <span className="text-[#C4B99F] italic">piano covers on Instagram</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Exploring <span className="text-[#D4C9B8] font-medium">Bayesian A/B testing frameworks</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Open to <span className="text-[#D4C9B8] font-medium">graduate roles · internships · freelance</span>
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Hero Section */}
      <div className="flex items-center gap-2 px-3 py-1.5 bg-[#EFEBE3] border-b-[0.5px] border-[#E0DAD0] text-[10px] font-medium tracking-[0.12em] uppercase text-[#999999]">
        hero
      </div>
      <section id="hero" className="grid grid-cols-1 md:grid-cols-2 min-h-[360px] bg-[#F7F4EF]">
        <div className="p-8 md:p-11 flex flex-col justify-center gap-[18px]">
          <span className="text-[11px] font-medium tracking-[0.1em] uppercase text-[#9B8B6E]">Data Professional · Melbourne</span>
          <h1 className="font-serif text-[42px] leading-[1.1] text-[#1A1814] m-0">Arun Krishnasamy</h1>
          <p className="text-[17px] text-[#5A5650] leading-[1.6] max-w-[440px] m-0">I&apos;m at the beginning of my story in data; but I show up curious, I stay until it makes sense, and I let the numbers do the talking.</p>
          <div className="flex gap-6 pt-2 mt-2 border-t-[0.5px] border-[#E0DAD0]">
            <div className="flex flex-col gap-0.5">
              <span className="font-serif text-[22px] text-[#1A1814]">12+</span>
              <span className="text-[11px] text-[#9B8B6E]">Datasets analysed</span>
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="font-serif text-[22px] text-[#1A1814]">4</span>
              <span className="text-[11px] text-[#9B8B6E]">End-to-end projects</span>
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="font-serif text-[22px] text-[#1A1814]">2</span>
              <span className="text-[11px] text-[#9B8B6E]">Tools built</span>
            </div>
          </div>
        </div>
        <div className="relative bg-[#E8E1D5] hidden md:flex items-center justify-center overflow-hidden">
          <div className="w-full h-full flex flex-col items-center justify-center gap-2 bg-gradient-to-br from-[#E8E1D5] to-[#D4C9B8] min-h-[260px]">
             <div className="w-[52px] h-[52px] rounded-full bg-[#C4B99F] flex items-center justify-center">
               <svg width="26" height="26" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="8" r="4" stroke="#9B8B6E" strokeWidth="1.5"/><path d="M4 20c0-4 3.6-7 8-7s8 3 8 7" stroke="#9B8B6E" strokeWidth="1.5" strokeLinecap="round"/></svg>
             </div>
             <span className="text-[12px] text-[#9B8B6E] font-medium">Your photo here</span>
          </div>
          <div className="absolute bottom-4 right-4 bg-[#F7F4EF] border-[0.5px] border-[#E0DAD0] rounded-full px-3.5 py-1.5 flex items-center gap-1.5 text-[11px] text-[#1A1814] font-medium">
            <div className="w-[7px] h-[7px] rounded-full bg-[#4CAF7E]"></div>
            Open to opportunities
          </div>
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Competency Map */}
      <div className="flex items-center gap-2 px-3 py-1.5 bg-[#EFEBE3] border-b-[0.5px] border-[#E0DAD0] text-[10px] font-medium tracking-[0.12em] uppercase text-[#999999]">
        competency map
      </div>
      <section className="bg-[#F7F4EF] p-8 md:p-12">
        <div className="flex justify-between items-start mb-8">
          <div>
            <h2 className="font-serif text-[28px] text-[#1A1814] m-0">The Data Professional Compass</h2>
            <p className="text-[12px] text-[#9B8B6E] italic mt-1">honest, self-assessed · hover each axis for breakdown</p>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 items-center">
          <div className="flex justify-center -mx-8 md:mx-0">
             <RadarChart data={radarData} />
          </div>
          <div className="flex flex-col gap-[13px]">
            {radarData.map((axis, i) => (
              <div key={i} className="flex flex-col gap-1.5">
                 <div className="flex justify-between">
                   <span className="text-[12px] font-medium text-[#1A1814]">{axis.competency}</span>
                   <span className="text-[11px] text-[#9B8B6E]">{axis.score}%</span>
                 </div>
                 <div className="h-[3px] bg-[#E0DAD0] rounded-full overflow-hidden w-full">
                    <div className="h-full bg-[#9B8B6E] rounded-full transition-all duration-1000 ease-out" style={{ width: `${axis.score}%` }}></div>
                 </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Work Evidence */}
      <div className="flex items-center gap-2 px-3 py-1.5 bg-[#EFEBE3] border-b-[0.5px] border-[#E0DAD0] text-[10px] font-medium tracking-[0.12em] uppercase text-[#999999]">
        work / evidence
      </div>
      <section className="bg-[#EFEBE3] p-8 md:p-12" id="work">
        <div className="mb-4">
          <h2 className="font-serif text-[28px] text-[#1A1814] m-0">Evidence</h2>
          <p className="text-[12px] text-[#9B8B6E] italic mt-1">analyses, models, and case studies</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 mt-7">
          {workProjects.length > 0 ? workProjects.map(project => (
            <div key={project.slug} className={`border-[0.5px] rounded-[10px] overflow-hidden ${project.isLive ? 'bg-[#F7F4EF] border-[#9B8B6E] border-[1.5px]' : 'bg-[#F7F4EF] border-[#D4C9B8]'}`}>
              {project.isLive ? (
                <div className="h-[86px] bg-[#E8E1D5] flex items-center justify-center gap-2.5 relative">
                  <div className="w-[60px] h-[42px] bg-[#1A1814] rounded flex flex-col justify-end p-1.5 gap-[2px]">
                    <div className="bg-[#9B8B6E] rounded-[1px] w-full h-[10px] opacity-50"></div>
                    <div className="bg-[#9B8B6E] rounded-[1px] w-full h-[16px] opacity-70"></div>
                    <div className="bg-[#9B8B6E] rounded-[1px] w-full h-[8px] opacity-40"></div>
                    <div className="bg-[#9B8B6E] rounded-[1px] w-full h-[20px] opacity-100"></div>
                  </div>
                  <div className="absolute top-[22px] right-[40px] w-2 h-2 rounded-full bg-[#9B8B6E] border-[1.5px] border-[#F7F4EF] shadow-sm animate-pulse"></div>
                </div>
              ) : (
                <div className="h-[86px] bg-[#E8E1D5] flex items-center justify-center">
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M3 17l4-8 4 4 4-6 4 6" stroke="#9B8B6E" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
                </div>
              )}
              <div className="p-3.5 flex flex-col justify-start">
                {project.isLive && (
                  <div className="inline-flex items-center gap-[5px] bg-[#1A1814] text-[#D4C9B8] text-[10px] font-medium px-2.5 py-1 rounded-full mb-2 self-start">
                    <div className="w-[5px] h-[5px] rounded-full bg-[#4CAF7E] animate-pulse"></div>
                    Live · Interactive
                  </div>
                )}
                {!project.isLive && (
                   <div className="text-[10px] font-medium tracking-[0.08em] uppercase text-[#9B8B6E] mb-[5px]">
                     {project.domain.slice(0, 2).join(' · ')}
                   </div>
                )}
                <div className="font-serif text-[14px] text-[#1A1814] leading-[1.3]">
                  {project.title}
                </div>
              </div>
            </div>
          )) : (
            <div className="text-[12px] italic text-[#9B8B6E]">No projects successfully compiled. Add Work marked entries to /content/projects/.</div>
          )}
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Process Section */}
      <div className="flex items-center gap-2 px-3 py-1.5 bg-[#EFEBE3] border-b-[0.5px] border-[#E0DAD0] text-[10px] font-medium tracking-[0.12em] uppercase text-[#999999]">
        how i think
      </div>
      <section className="bg-[#1A1814] p-8 md:p-12">
        <h2 className="font-serif text-[28px] text-[#F7F4EF] m-0 mb-1.5">How I approach a data problem</h2>
        <p className="text-[12px] text-[#5A5650] italic mb-9">the thinking behind the work</p>
        
        <div className="grid grid-cols-1 md:grid-cols-4">
           {/* Step 1 */}
           <div className="px-5 py-[22px] border-l-0 md:border-l-[0.5px] border-t-[0.5px] md:border-t-0 border-[#2E2A25] first:border-l-0 first:border-t-0 flex flex-col">
             <div className="font-serif text-[34px] text-[#6B7280] leading-none mb-3.5">01</div>
             <div className="text-[13px] font-medium text-[#D4C9B8] mb-[7px]">Understand before touching</div>
             <div className="text-[12px] text-[#5A5650] leading-[1.6]">Frame the question. Challenge the brief. <span className="text-[#9B8B6E] italic">A wrong question answered perfectly is still wrong.</span></div>
           </div>
           {/* Step 2 */}
           <div className="px-5 py-[22px] border-l-0 md:border-l-[0.5px] border-t-[0.5px] md:border-t-0 border-[#2E2A25] flex flex-col">
             <div className="font-serif text-[34px] text-[#6B7280] leading-none mb-3.5">02</div>
             <div className="text-[13px] font-medium text-[#D4C9B8] mb-[7px]">Let the data speak first</div>
             <div className="text-[12px] text-[#5A5650] leading-[1.6]">EDA before assumptions. <span className="text-[#9B8B6E] italic">The data usually knows something you don't.</span></div>
           </div>
           {/* Step 3 */}
           <div className="px-5 py-[22px] border-l-0 md:border-l-[0.5px] border-t-[0.5px] md:border-t-0 border-[#2E2A25] flex flex-col">
             <div className="font-serif text-[34px] text-[#6B7280] leading-none mb-3.5">03</div>
             <div className="text-[13px] font-medium text-[#D4C9B8] mb-[7px]">Model with intent</div>
             <div className="text-[12px] text-[#5A5650] leading-[1.6]">Right tool, not flashiest. <span className="text-[#9B8B6E] italic">Interpretability often matters more than accuracy.</span></div>
           </div>
           {/* Step 4 */}
           <div className="px-5 py-[22px] border-l-0 md:border-l-[0.5px] border-t-[0.5px] md:border-t-0 border-[#2E2A25] flex flex-col">
             <div className="font-serif text-[34px] text-[#6B7280] leading-none mb-3.5">04</div>
             <div className="text-[13px] font-medium text-[#D4C9B8] mb-[7px]">Make it land</div>
             <div className="text-[12px] text-[#5A5650] leading-[1.6]">Speak to people who don't think in p-values. <span className="text-[#9B8B6E] italic">Insight that isn't understood isn't insight.</span></div>
           </div>
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Sandbox Grid with Music Card */}
      <div className="flex items-center gap-2 px-3 py-1.5 bg-[#EFEBE3] border-b-[0.5px] border-[#E0DAD0] text-[10px] font-medium tracking-[0.12em] uppercase text-[#999999]">
        sandbox <span className="bg-[#4CAF7E] text-[#F7F4EF] text-[9px] px-[7px] py-[2px] rounded-full tracking-[0.08em] ml-1">updated</span>
      </div>
      <section className="bg-[#F7F4EF] p-8 md:p-12" id="sandbox">
        <div>
          <h2 className="font-serif text-[28px] text-[#1A1814] m-0">Sandbox</h2>
          <p className="text-[12px] text-[#9B8B6E] italic mt-1">experiments, tools, and things built for fun</p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5 mt-7">
           {/* Fallback Sandbox Dummy Cards */}
           <div className="bg-[#EFEBE3] border-[0.5px] border-[#D4C9B8] rounded-[10px] p-5 flex gap-3.5 items-start">
             <div className="w-9 h-9 rounded-lg bg-[#D4C9B8] flex items-center justify-center shrink-0">
               <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="3" stroke="#5A5650" strokeWidth="1.5"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3" stroke="#5A5650" strokeWidth="1.5" strokeLinecap="round"/></svg>
             </div>
             <div className="flex flex-col">
               <span className="font-serif text-[15px] text-[#1A1814] mb-1">Stat Intuition Trainer</span>
               <span className="text-[12px] text-[#5A5650] leading-[1.5]">Interactive demos for Bayesian vs Frequentist reasoning. Move sliders, build intuition.</span>
             </div>
           </div>
           <div className="bg-[#EFEBE3] border-[0.5px] border-[#D4C9B8] rounded-[10px] p-5 flex gap-3.5 items-start">
             <div className="w-9 h-9 rounded-lg bg-[#D4C9B8] flex items-center justify-center shrink-0">
               <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><polyline points="16 18 22 12 16 6" stroke="#5A5650" strokeWidth="1.5" strokeLinecap="round"/><polyline points="8 6 2 12 8 18" stroke="#5A5650" strokeWidth="1.5" strokeLinecap="round"/></svg>
             </div>
             <div className="flex flex-col">
               <span className="font-serif text-[15px] text-[#1A1814] mb-1">Dataset Explorer CLI</span>
               <span className="text-[12px] text-[#5A5650] leading-[1.5]">A Python tool for instant EDA with one command from your terminal.</span>
             </div>
           </div>

           {/* The 2-span Music Card */}
           <div className="col-span-1 md:col-span-2 bg-[#EFEBE3] border-[0.5px] border-[#D4C9B8] rounded-[10px] p-0 overflow-hidden grid grid-cols-1 md:grid-cols-[200px_1fr]">
              <div className="bg-[#1A1814] flex flex-col items-center justify-center gap-3 py-7 px-5 relative overflow-hidden h-[180px] md:h-auto">
                 <div className="flex items-end gap-[3px] h-8">
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-100"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-300"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-200"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-500"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-400"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-600"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-200"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-800"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-700"></div>
                   <div className="w-1 bg-[#9B8B6E] opacity-70 rounded-full animate-wave delay-300"></div>
                 </div>
                 <span className="text-[10px] text-[#5A5650] tracking-[0.1em] uppercase text-center">where the data<br/>brain goes to rest</span>
                 <span className="text-[11px] text-[#9B8B6E] font-medium border-[0.5px] border-[#2E2A25] px-3 py-1 rounded-full">@yourhandle</span>
              </div>
              <div className="p-6 md:p-6 flex flex-col justify-center gap-2">
                 <span className="text-[10px] font-medium tracking-[0.1em] uppercase text-[#9B8B6E]">Beyond the notebook</span>
                 <h3 className="font-serif text-[18px] text-[#1A1814] leading-[1.3] m-0">Guitar and piano. Always learning, always playing.</h3>
                 <div className="flex gap-2 flex-wrap mt-2">
                   <span className="text-[10px] text-[#9B8B6E] border-[0.5px] border-[#D4C9B8] px-2.5 py-[3px] rounded-full bg-[#F7F4EF]">Guitar</span>
                   <span className="text-[10px] text-[#9B8B6E] border-[0.5px] border-[#D4C9B8] px-2.5 py-[3px] rounded-full bg-[#F7F4EF]">Piano</span>
                 </div>
              </div>
           </div>
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Writing Log */}
      <div className="flex items-center gap-2 px-3 py-1.5 bg-[#EFEBE3] border-b-[0.5px] border-[#E0DAD0] text-[10px] font-medium tracking-[0.12em] uppercase text-[#999999]">
        writing / the log
      </div>
      <section className="bg-[#EFEBE3] p-8 md:p-12 mb-auto" id="writing">
        <div className="mb-7">
          <h2 className="font-serif text-[28px] text-[#1A1814] m-0">The Log</h2>
          <p className="text-[12px] text-[#9B8B6E] italic mt-1">thinking out loud about data, statistics, and the craft</p>
        </div>
        
        <div className="flex flex-col border-t-[0.5px] border-[#D4C9B8]">
           {writingPosts.length > 0 ? writingPosts.map(post => (
             <div key={post.slug} className="flex justify-between items-center py-[18px] border-b-[0.5px] border-[#D4C9B8] group cursor-pointer hover:bg-black/5 px-2 -mx-2 transition-colors rounded-sm">
               <div className="flex flex-col gap-1">
                 <span className="text-[10px] font-medium tracking-[0.08em] uppercase text-[#9B8B6E]">{post.domain[0]}</span>
                 <span className="font-serif text-[16px] text-[#1A1814] group-hover:underline decoration-[0.5px] underline-offset-4">{post.title}</span>
               </div>
               <div className="flex flex-col items-end gap-1 shrink-0 ml-4">
                 <span className="text-[11px] text-[#9B8B6E] text-right">{post.shortDate || '2026'}</span>
                 <span className="text-[14px] text-[#9B8B6E] group-hover:translate-x-1 transition-transform">→</span>
               </div>
             </div>
           )) : (
             <div className="py-4 text-[#9B8B6E] text-[12px] italic border-b-[0.5px] border-[#D4C9B8]">
               No publishing history detected. Add raw `.mdx` files to `/content/projects` marked as "Writing".
             </div>
           )}
        </div>
      </section>

    </main>
  );
}
