import fs from 'fs';
import path from 'path';
import { projects as veliteProjects } from '#velite';
import RadarChart from '@/components/RadarChart';
import CompassHeader from '@/components/CompassHeader';
import Image from 'next/image';
import LiveTelemetry from '@/components/LiveTelemetry';
import ProcessSection from '@/components/ProcessSection';
import BuiltForFunList from '@/components/BuiltForFunList';
import Link from 'next/link';
import { getProjects, getExperiments } from '@/lib/data';

export default async function Home() {
  // Load decoupled aggregated scores generated by the LLM Delta pipeline
  let radarData: any[] = [];
  try {
    const scoresPath = path.join(process.cwd(), 'public', 'scores.json');
    radarData = JSON.parse(fs.readFileSync(scoresPath, 'utf8'));
  } catch (error) {
    console.error("Failed to load scores.json", error);
  }

  // Load new filesystem data
  const workProjects = await getProjects();
  const experiments = await getExperiments();
  
  // Sort radarData in descending order by score
  const sortedRadarData = [...radarData].sort((a, b) => b.score - a.score);

  // Velite posts for the blog section
  const writingPosts = veliteProjects.filter(p => p.category === 'Writing');

  return (
    <main className="w-full flex-1 flex flex-col">
      
      {/* Ticker Section */}
      <div className="bg-[#1A1814] overflow-hidden py-[9px] border-b-[0.5px] border-[#2E2A25]">
        <div className="flex whitespace-nowrap animate-[ticker_28s_linear_infinite]">
          {[...Array(2)].map((_, i) => (
            <div key={i} className="contents">
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Now reading <span className="text-[#D4C9B8] font-medium">Designing Data-Intensive Applications</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Building <span className="text-[#D4C9B8] font-medium">churn prediction model in sklearn</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Learning <span className="text-[#D4C9B8] font-medium">dbt Core + Airflow orchestration</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Unwinding with <span className="text-[#C4B99F] italic">piano covers on Instagram</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Exploring <span className="text-[#D4C9B8] font-medium">Bayesian A/B testing frameworks</span>
              </span>
              <span className="inline-flex items-center gap-2.5 px-7 text-[11px] text-[#9B8B6E] tracking-[0.04em]">
                <span className="w-1 h-1 rounded-full bg-[#5A5650] shrink-0"></span>
                Open to <span className="text-[#D4C9B8] font-medium">graduate roles · internships · freelance</span>
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* Hero Section */}
      <section id="hero" className="grid grid-cols-1 md:grid-cols-2 min-h-[360px] bg-[#F7F4EF]">
        <div className="p-8 md:p-11 flex flex-col justify-center gap-[18px]">
          <span className="text-[11px] font-medium tracking-[0.1em] uppercase text-[#9B8B6E]">Data Professional · Melbourne</span>
          <h1 className="font-serif text-[42px] leading-[1.1] text-[#1A1814] m-0">Arun Krishnasamy</h1>
          <p className="text-[17px] text-[#5A5650] leading-[1.6] max-w-[440px] m-0">I&apos;m at the beginning of my story in data; but I show up curious, I stay until it makes sense, and I let the numbers do the talking.</p>
          <LiveTelemetry />
        </div>
        <div className="relative bg-[#E8E1D5] flex items-center justify-center p-8 md:p-0 overflow-hidden">
          <div className="relative w-full max-w-md mx-auto md:max-w-none md:w-full aspect-[4/5] lg:aspect-[3/4] overflow-hidden rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.08)] transition-transform duration-500 hover:scale-[1.02]">
            
            {/* The Status Tag - Anchored Top Right */}
            <div className="absolute top-6 right-6 z-10 bg-green-50/90 backdrop-blur-md text-green-800 text-xs font-semibold px-4 py-2 rounded-full flex items-center gap-2 shadow-sm border border-green-100/50">
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-green-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-green-500"></span>
              </span>
              Open to opportunities
            </div>

            <Image
              src="/images/profile-headshot.png"
              alt="Arun Krishnasamy - Data Professional"
              fill
              priority
              className="object-cover object-center grayscale-[20%] hover:grayscale-0 transition-all duration-700"
              sizes="(max-width: 768px) 100vw, 50vw"
            />
          </div>
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Competency Map */}
      <section className="bg-[#F7F4EF] p-8 md:p-12">
        <CompassHeader />
        <div className="grid grid-cols-1 md:grid-cols-2 gap-10 items-center">

          <div className="flex justify-center -mx-8 md:mx-0">
             <RadarChart data={radarData} />
          </div>
          <div className="flex flex-col gap-[13px]">
            {sortedRadarData.map((axis, i) => (
              <div key={i} className="flex flex-col gap-1.5">
                 <div className="flex justify-between">
                   <span className="text-[12px] font-medium text-[#1A1814]">{axis.competency}</span>
                   <span className="text-[11px] text-[#9B8B6E]">{axis.score}%</span>
                 </div>
                 <div className="h-[3px] bg-[#E0DAD0] rounded-full overflow-hidden w-full">
                    <div className="h-full bg-[#9B8B6E] rounded-full transition-all duration-1000 ease-out" style={{ width: `${axis.score}%` }}></div>
                 </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Projects Section */}
      <section className="bg-[#EFEBE3] p-8 md:p-12" id="projects">
        <div className="mb-4">
          <h2 className="font-serif text-[28px] text-[#1A1814] m-0">Projects</h2>
          <p className="text-[12px] text-[#9B8B6E] italic mt-1">analyses, models, and case studies</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 mt-7">
          {workProjects.length > 0 ? workProjects.map(project => (
            <Link 
              key={project.slug} 
              href={`/projects/${project.slug}`}
              className={`border-[0.5px] rounded-[10px] overflow-hidden group transition-all hover:shadow-lg ${project.status === 'Live' ? 'bg-[#F7F4EF] border-[#9B8B6E] border-[1.5px]' : 'bg-[#F7F4EF] border-[#D4C9B8]'}`}
            >
              <div className="h-[86px] bg-[#E8E1D5] flex items-center justify-center relative overflow-hidden">
                {project.media ? (
                  <Image src={project.media} alt={project.name} fill className="object-cover opacity-50 group-hover:opacity-100 transition-opacity" />
                ) : (
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M3 17l4-8 4 4 4-6 4 6" stroke="#9B8B6E" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
                )}
                {project.status === 'Live' && (
                  <div className="absolute top-[22px] right-[40px] w-2 h-2 rounded-full bg-[#9B8B6E] border-[1.5px] border-[#F7F4EF] shadow-sm animate-pulse"></div>
                )}
              </div>
              <div className="p-3.5 flex flex-col justify-start">
                {project.status === 'Live' && (
                  <div className="inline-flex items-center gap-[5px] bg-[#1A1814] text-[#D4C9B8] text-[10px] font-medium px-2.5 py-1 rounded-full mb-2 self-start">
                    <div className="w-[5px] h-[5px] rounded-full bg-[#4CAF7E] animate-pulse"></div>
                    Live · Interactive
                  </div>
                )}
                <div className="text-[10px] font-medium tracking-[0.08em] uppercase text-[#9B8B6E] mb-[5px]">
                  {project.stack.slice(0, 2).join(' · ')}
                </div>
                <div className="font-serif text-[14px] text-[#1A1814] leading-[1.3] group-hover:underline">
                  {project.name}
                </div>
              </div>
            </Link>
          )) : (
            <div className="text-[12px] italic text-[#9B8B6E]">No projects successfully compiled. Add Work marked entries to /content/projects/.</div>
          )}
        </div>
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Process Section */}
      <ProcessSection />

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Built for fun Section */}
      <section className="bg-[#F7F4EF] p-0" id="built-for-fun">
        <div className="p-8 md:p-12 pb-4">
          <h2 className="font-serif text-[28px] text-[#1A1814] m-0">Built for fun</h2>
          <p className="text-[12px] text-[#9B8B6E] italic mt-1">experiments, tools, and things built for fun</p>
        </div>
        
        <BuiltForFunList experiments={experiments} />
      </section>

      <div className="h-[0.5px] bg-[#E0DAD0] w-full"></div>

      {/* Blog Section */}
      <section className="bg-[#EFEBE3] p-8 md:p-12 mb-auto" id="blog">
        <div className="mb-7">
          <h2 className="font-serif text-[28px] text-[#1A1814] m-0">Blog</h2>
          <p className="text-[12px] text-[#9B8B6E] italic mt-1">thinking out loud about data, statistics, and the craft</p>
        </div>
        
        <div className="flex flex-col border-t-[0.5px] border-[#D4C9B8]">
           {writingPosts.length > 0 ? writingPosts.map(post => (
             <div key={post.slug} className="flex justify-between items-center py-[18px] border-b-[0.5px] border-[#D4C9B8] group cursor-pointer hover:bg-black/5 px-2 -mx-2 transition-colors rounded-sm">
               <div className="flex flex-col gap-1">
                 <span className="text-[10px] font-medium tracking-[0.08em] uppercase text-[#9B8B6E]">{post.domain[0]}</span>
                 <span className="font-serif text-[16px] text-[#1A1814] group-hover:underline decoration-[0.5px] underline-offset-4">{post.title}</span>
               </div>
               <div className="flex flex-col items-end gap-1 shrink-0 ml-4">
                 <span className="text-[11px] text-[#9B8B6E] text-right">{post.shortDate || '2026'}</span>
                 <span className="text-[14px] text-[#9B8B6E] group-hover:translate-x-1 transition-transform">→</span>
               </div>
             </div>
           )) : (
             <div className="py-4 text-[#9B8B6E] text-[12px] italic border-b-[0.5px] border-[#D4C9B8]">
               No publishing history detected. Add raw `.mdx` files to `/content/projects` marked as "Writing".
             </div>
           )}
        </div>
      </section>

    </main>
  );
}
